[package]
name = "mojoio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.24"
log = "0.4.17"
thiserror = "1.0.31"
parking_lot = {version = "0.12", features=["serde"]}